 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Abrams, Adam W.','Employee',66300.00,'Per Annum','WESTERN REGIONAL COMMUNICATIONS DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Adams, Ian H.','Employee',45000.00,'Per Annum','EXECUTIVE ASSISTANT TO THE DIRECTOR OF SCHEDULING AND ADVANCE');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Agnew, David P.','Employee',93840.00,'Per Annum','DEPUTY DIRECTOR OF INTERGOVERNMENTAL AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Albino, James ','Employee',91800.00,'Per Annum','SENIOR PROGRAM MANAGER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Aldy, Jr., Joseph E.','Employee',130500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT FOR ENERGY AND ENVIRONMENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Alley, Hilary J.','Employee',42000.00,'Per Annum','STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Amorsingh, Lucius L.','Employee',56092.00,'Per Annum','SPECIAL ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Anderson, Amanda D.','Employee',60000.00,'Per Annum','SPECIAL ASSISTANT TO THE CHIEF OF STAFF');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Anderson, Charles D.','Employee',51000.00,'Per Annum','POLICY ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Andrias, Kate E.','Employee',130500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND ASSOCIATE COUNSEL TO THE PRESIDENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Anello, Russell M.','Employee',66300.00,'Per Annum','COUNSEL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Asen, Jonathan D.','Employee',42000.00,'Per Annum','SENIOR ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Attili, Candice L.','Employee',58511.00,'Per Annum','ASSISTANT SHIFT LEADER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Axelrod, David M.','Employee',172200.00,'Per Annum','ASSISTANT TO THE PRESIDENT AND SENIOR ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Ayling, Lindsay A.','Employee',42000.00,'Per Annum','ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Baggetto, Maude L.','Employee',42000.00,'Per Annum','STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Baldassaro, Frederick J.','Detailee',122744.00,'Per Annum','COMMUNICATIONS DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Barnes, Melody C.','Employee',172200.00,'Per Annum','ASSISTANT TO THE PRESIDENT AND DIRECTOR OF THE DOMESTIC POLICY COUNCIL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Baskerville, Jr., Chester A.','Employee',47532.00,'Per Annum','ASSISTANT SHIFT LEADER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Bassin, Ian M.','Employee',99000.00,'Per Annum','DEPUTY ASSOCIATE COUNSEL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Bates, Andrew J.','Employee',42000.00,'Per Annum','MEDIA MONITOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Bauer, Nicholas T.','Employee',55000.00,'Per Annum','ASSOCIATE DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Bauer, Robert F.','Employee',172200.00,'Per Annum','ASSISTANT TO THE PRESIDENT AND COUNSEL TO THE PRESIDENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Becnel, Bradley D.','Employee',55000.00,'Per Annum','SPECIAL ASSISTANT AND ADVANCE LEAD');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Bedingfield, Katherine J.','Employee',90000.00,'Per Annum','DEPUTY DIRECTOR FOR MEDIA AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Beinart, Diana H.','Employee',130500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND ASSOCIATE COUNSEL TO THE PRESIDENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Belive, Lauren E.','Employee',45000.00,'Per Annum','LEGISLATIVE ASSISTANT AND ASSISTANT FOR EVENTS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Beliveau, Emmett S.','Employee',130000.00,'Per Annum','DEPUTY ASSISTANT TO THE PRESIDENT AND DIRECTOR OF ADVANCE AND OPERATIONS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Bernard, Sarah C.','Employee',70000.00,'Per Annum','DIRECTOR, ONLINE ENGAGEMENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Beverly, Alaina C.','Employee',71400.00,'Per Annum','ASSOCIATE DIRECTOR OF URBAN AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Bhowmik, Rachana','Employee',100000.00,'Per Annum','DIRECTOR OF SPECIAL PROJECTS AND SPECIAL ASSISTANT TO THE OFFICE OF THE CHIEF OF STAFF');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Binns, Mary U.','Employee',70126.00,'Per Annum','SPECIAL ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Birdsall, Kristen S.','Employee',45900.00,'Per Annum','RESEARCHER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Bisi, Rachel I.','Employee',42000.00,'Per Annum','LEGISLATIVE ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Blake, Michael A.','Employee',61200.00,'Per Annum','DEPUTY ASSOCIATE DIRECTOR OF INTERGOVERNMENTAL AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Block, Michael R.','Employee',42000.00,'Per Annum','STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Blount, Patricia H.','Employee',44402.00,'Per Annum','RECORDS MANAGEMENT ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Bond, Brian K.','Employee',93840.00,'Per Annum','DEPUTY DIRECTOR OF PUBLIC ENGAGEMENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Bookey-Baker, Natalie F.','Employee',45000.00,'Per Annum','EXECUTIVE ASSISTANT TO THE CHIEF OF STAFF TO THE FIRST LADY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Branch, Katherine Y.','Employee',61200.00,'Per Annum','SPECIAL ASSISTANT TO THE SENIOR ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Brennan, John O.','Employee',172200.00,'Per Annum','ASSISTANT TO THE PRESIDENT FOR HOMELAND SECURITY AND COUNTERTERRORISM');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Bressler, Steven Y.','Detailee',148510.00,'Per Annum','CLEARANCE ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Brewer, Anne P.','Employee',45000.00,'Per Annum','EXECUTIVE ASSISTANT TO THE DIRECTOR OF PUBLIC ENGAGEMENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Brooke, Mary J.','Employee',89033.00,'Per Annum','SUPERVISOR OF CORRESPONDENCE REVIEW');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Brown, Elizabeth M.','Employee',172200.00,'Per Annum','ASSISTANT TO THE PRESIDENT AND STAFF SECRETARY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Browner, Carol M.','Employee',172200.00,'Per Annum','ASSISTANT TO THE PRESIDENT FOR ENERGY AND CLIMATE CHANGE');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Brundage, Amy J.','Employee',78000.00,'Per Annum','ASSISTANT PRESS SECRETARY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Brush, Michael P.','Employee',56100.00,'Per Annum','SPECIAL ASSISTANT AND ADVANCE LEAD');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Buffett, Howard W.','Detailee',51630.00,'Per Annum','POLICY ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Burman, Kendall C.','Employee',130500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND ASSOCIATE COUNSEL TO THE PRESIDENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Burnough, Erinn J.','Employee',66300.00,'Per Annum','DEPUTY DIRECTOR AND DEPUTY SOCIAL SECRETARY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Burton, William A.','Employee',113000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND DEPUTY PRESS SECRETARY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Campbell, Frances L.','Employee',100904.00,'Per Annum','SUPERVISOR, DOCUMENT MANAGEMENT AND TRACKING UNIT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Campbell, Grant E.','Employee',45900.00,'Per Annum','ASSOCIATE DIRECTOR AND TRIP COORDINATOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Campbell, Nnaji-Semayi K.','Employee',42000.00,'Per Annum','SENIOR ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Campos, David R.','Employee',42000.00,'Per Annum','ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Campoverdi, Alejandra M.','Employee',60000.00,'Per Annum','SPECIAL ASSISTANT TO THE DEPUTY CHIEF OF STAFF');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Camu?ñez, Michael C.','Employee',140000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND SPECIAL COUNSEL TO THE PRESIDENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Canery, Beverly D.','Employee',58511.00,'Per Annum','ASSISTANT SHIFT LEADER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Carden, Meredith M.','Employee',42000.00,'Per Annum','STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Cardwell, Rebecca A.','Employee',43656.00,'Per Annum','OPERATOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Carrier, Ethan A.','Detailee',94969.00,'Per Annum','ETHICS ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Carter, Rhonda M.','Employee',57000.00,'Per Annum','SPECIAL ASSISTANT TO THE WHITE HOUSE COUNSEL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Castillo, Laura M.','Employee',42000.00,'Per Annum','ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Chaifetz, Samantha L.','Detailee',123758.00,'Per Annum','RESEARCHER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Chambers, Caroline M.','Employee',120000.00,'Per Annum','DIRECTOR OF CONFIRMATIONS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Chen, Margaret C.','Employee',0.00,'Per Annum','SPECIAL ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Cherlin, Reid H.','Employee',78000.00,'Per Annum','ASSISTANT PRESS SECRETARY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Chhabra, Anand','Employee',42000.00,'Per Annum','STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Chiodo, Theodore A.','Employee',60000.00,'Per Annum','ASSISTANT STAFF SECRETARY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Cizner, Jennifer C.','Employee',85680.00,'Per Annum','DEPUTY CHIEF OF STAFF FOR PRESIDENTIAL PERSONNEL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Clarke, Kay F.','Employee',64439.00,'Per Annum','SHIFT LEADER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Claude, Lilia H.','Employee',58511.00,'Per Annum','ASSISTANT SHIFT LEADER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Cobbina, Kwesi A.','Employee',42000.00,'Per Annum','STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Cohen, Elizabeth S','Employee',45900.00,'Per Annum','ASSOCIATE DIRECTOR AND SCHEDULING RESEARCHER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Cokley, Rebecca A.','Employee',72000.00,'Per Annum','PRIORITY PLACEMENT DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Colvin, Nicholas M.','Employee',63240.00,'Per Annum','SPECIAL ASSISTANT TO THE WHITE HOUSE COUNSEL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Conrad, Shasti K. ','Employee',42000.00,'Per Annum','STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Corrigan, Tara C.','Employee',45000.00,'Per Annum','EXECUTIVE ASSISTANT TO THE POLITICAL DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Coven, Martha B.','Employee',120000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT FOR MOBILTY AND OPPORTUNITY POLICY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Crowley, Jeffrey S.','Employee',102000.00,'Per Annum','DIRECTOR OF THE OFFICE OF NATIONAL AIDS POLICY AND SENIOR ADVISOR ON DISABILITY POLICY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Crutchfield, Danielle M.','Employee',130000.00,'Per Annum','DEPUTY ASSISTANT TO THE PRESIDENT AND DIRECTOR OF APPOINTMENTS AND SCHEDULING');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Cuba, Juan C.','Employee',42000.00,'Per Annum','STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Cuellar, Martin E.','Employee',91800.00,'Per Annum','DEPUTY DIRECTOR, PRESIDENTIAL CORRESPONDENCE');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Cunningham, Jason F.','Detailee',64548.00,'Per Annum','RESEARCHER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Cunningham, Vinson T.','Employee',42000.00,'Per Annum','ECONOMICS STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Cusack, David J.','Employee',102000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND DEPUTY DIRECTOR OF ADVANCE');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Cushman, Chase M.','Employee',45900.00,'Per Annum','ASSOCIATE DIRECTOR OF SCHEDULING');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Cutter, Stephanie ','Employee',172200.00,'Per Annum','ASSISTANT TO THE PRESIDENT FOR SPECIAL PROJECTS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Dale, Kareem A.','Employee',61200.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND DEPUTY ASSOCIATE DIRECTOR OF PUBLIC ENGAGEMENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Dalheim, Karen L.','Detailee',148510.00,'Per Annum','ETHICS ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Davies, Susan M.','Employee',158500.00,'Per Annum','DEPUTY ASSISTANT TO THE PRESIDENT AND DEPUTY COUNSEL TO THE PRESIDENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Davis, Christopher E.','Employee',76500.00,'Per Annum','SENIOR LEGISLATIVE AFFAIRS ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('De Sio, Jr., Henry F.','Employee',153300.00,'Per Annum','DEPUTY ASSISTANT TO THE PRESIDENT FOR MANAGEMENT AND ADMINISTRATION');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Deese, Brian C.','Employee',130500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT FOR ECONOMIC POLICY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('DeGuzman, Jr., Danilo','Employee',72876.00,'Per Annum','PRESIDENTIAL SUPPORT SPECIALIST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('DeGuzman, Brian K.','Employee',42738.00,'Per Annum','OPERATOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('DeParle, Nancy-Ann Min','Employee',158500.00,'Per Annum','COUNSELOR TO THE PRESIDENT AND DIRECTOR OF THE WHITE HOUSE OFFICE FOR HEALTH CARE REFORM');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('DeRosa, Mary B.','Employee',158500.00,'Per Annum','DEPUTY ASSISTANT TO THE PRESIDENT AND DEPUTY COUNSEL TO THE PRESIDENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Devine, Carrie S.','Employee',56100.00,'Per Annum','SPECIAL ASSISTANT AND ADVANCE LEAD');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Dillon, Michael P.','Employee',113000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND DEPUTY DIRECTOR OF POLITICAL AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Donilon, Thomas E.','Employee',172200.00,'Per Annum','ASSISTANT TO THE PRESIDENT AND DEPUTY NATIONAL SECURITY ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Donovan, Michael W.','Employee',45900.00,'Per Annum','ASSOCIATE DIRECTOR AND SCHEDULING RESEARCHER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Donovan, William J.','Employee',42000.00,'Per Annum','ENERGY AND ENVIRONMENT STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Dorsett, Craig M.','Employee',42000.00,'Per Annum','ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Douglas, Derek R. B.','Employee',120000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT FOR URBAN AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Droege, Philip C.','Employee',140259.00,'Per Annum','DIRECTOR OF RECORDS MANAGEMENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('DuBois, Joshua P.','Employee',100000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND EXECUTIVE DIRECTOR OF THE WHITE HOUSE OFFICE OF FAITH-BASED AND NEIGHBORHOOD PARTNERSHIPS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Dunn, Lauren P.','Employee',50000.00,'Per Annum','POLICY ASSISTANT, URBAN POLICY AND MOBILITY AND OPPORTUNITY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Dyer, Deesha A.','Employee',45000.00,'Per Annum','ASSOCIATE DIRECTOR FOR SCHEDULING CORRESPONDENCE');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Ealons, Corey A.','Employee',79560.00,'Per Annum','DIRECTOR OF AFRICAN AMERICAN MEDIA');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Earnest, Joshua R.','Employee',113000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND DEPUTY PRESS SECRETARY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Edgerton, Erin M.','Detailee',89033.00,'Per Annum','NEW MEDIA ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Edmonds, Anita J.','Employee',49069.00,'Per Annum','RECORDS MANAGEMENT ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Edwards, Lisa W.','Detailee',155500.00,'Per Annum','DEPUTY ASSOCIATE COUNSEL FOR PRESIDENTIAL PERSONNEL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Eisen, Norman L.','Employee',149000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND SPECIAL COUNSEL TO THE PRESIDENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Emanuel, Rahm I.','Employee',172200.00,'Per Annum','ASSISTANT TO THE PRESIDENT AND CHIEF OF STAFF');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Escobar, Felicia A. ','Employee',90000.00,'Per Annum','SENIOR POLICY ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Espinel, Zulima L.','Employee',130500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND ASSOCIATE COUNSEL TO THE PRESIDENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Farrell, Diana','Employee',147500.00,'Per Annum','DEPUTY ASSISTANT TO THE PRESIDENT FOR ECONOMIC POLICY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Faulman, Michael T.','Employee',42000.00,'Per Annum','ADVANCE COORDINATOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Favreau, Jonathan E.','Employee',172200.00,'Per Annum','ASSISTANT TO THE PRESIDENT AND DIRECTOR OF SPEECHWRITING');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Fenn, Sarah B.','Employee',42000.00,'Per Annum','STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Fergenson, Micah F.','Employee',42000.00,'Per Annum','STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Fernandez, Micaela J.','Employee',102000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND DIRECTOR OF EVENTS AND PROTOCOL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Fernkas, Robin E.','Detailee',126251.00,'Per Annum','POLICY ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Finkenbinder, Benjamin N.','Employee',45900.00,'Per Annum','ASSOCIATE DIRECTOR OF PRESS ADVANCE AND PRESS POOL WRANGLER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Finlen, Shawn T.','Employee',50000.00,'Per Annum','ASSISTANT DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Firestone, Daren H.','Detailee',105211.00,'Per Annum','DEPUTY ASSOCIATE COUNSEL FOR PRESIDENTIAL PERSONNEL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Fiscus, Taylor R.','Employee',45000.00,'Per Annum','ASSOCIATE DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Fitts, Alan 0.','Employee',61200.00,'Per Annum','DEPUTY DIRECTOR OF ADVANCE AND TRIP DIRECTOR FOR THE FIRST LADY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Flatgard, Benjamin W.','Employee',55000.00,'Per Annum','ECONOMICS DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Ford, Harrison A.','Employee',42000.00,'Per Annum','SENIOR ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Frank, April P.','Employee',42000.00,'Per Annum','STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Frankel, Adam P.','Employee',100000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND SENIOR PRESIDENTIAL SPEECHWRITER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Freeman, Myra B.','Employee',73917.00,'Per Annum','RECORDS MANAGEMENT ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Frye, Jocelyn C.','Employee',140000.00,'Per Annum','DEPUTY ASSISTANT TO THE PRESIDENT AND DIRECTOR OF POLICY AND PROJECTS FOR THE FIRST LADY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Furman, Jason L.','Employee',147500.00,'Per Annum','DEPUTY ASSISTANT TO THE PRESIDENT  FOR ECONOMIC POLICY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Gage, Peter T.','Detailee',94969.00,'Per Annum','POLICY ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Garcia, Kristin M.','Employee',45000.00,'Per Annum','LEGISLATIVE ASSISTANT AND ASSISTANT TO THE SENATE LIAISON');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Gardaphe, Frederico C.','Employee',50000.00,'Per Annum','ASSISTANT DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Gaspard, Patrick H.','Employee',172200.00,'Per Annum','ASSISTANT TO THE PRESIDENT AND DIRECTOR OF POLITICAL AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Gavin, Jr., Thomas E.','Employee',102000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND DIRECTOR OF MEDIA AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Gibbs, Robert L.','Employee',172200.00,'Per Annum','ASSISTANT TO THE PRESIDENT AND PRESS SECRETARY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Gillette, Jodi A.','Employee',71400.00,'Per Annum','DEPUTY ASSOCIATE DIRECTOR OF INTERGOVERNMENTAL AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Godfrey, Harrison T.','Employee',42000.00,'Per Annum','LEGISLATIVE ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Gomez, David F.','Employee',45000.00,'Per Annum','RESEARCHER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Gonzalez, Roberto J.','Employee',114000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND  ASSOCIATE COUNSEL TO THE PRESIDENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Goodman, Jennifer','Employee',63240.00,'Per Annum','DEPUTY DIRECTOR OF SCHEDULING AND EVENTS COORDINATOR FOR THE FIRST LADY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Goodman, Mary B.','Employee',130500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT FOR FINANCIAL MARKETS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Gottlieb, Graham D.','Employee',42000.00,'Per Annum','BOARDS AND COMMISSIONS STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Gottlieb, Michael J.','Employee',114000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND ASSOCIATE COUNSEL TO THE PRESIDENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Gottry, Heather C.','Detailee',136134.00,'Per Annum','ASSOCIATE COUNSEL TO THE PRESIDENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Graham, Lottie B.','Employee',63673.00,'Per Annum','ASSISTANT SHIFT LEADER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Grant, Kathryn A.','Employee',42000.00,'Per Annum','ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Gray, Danielle C.','Employee',130500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND ASSOCIATE COUNSEL TO THE PRESIDENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Green, Jason G.','Employee',99000.00,'Per Annum','DEPUTY ASSOCIATE COUNSEL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Green, Valerie E.','Employee',113000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT FOR PRESIDENTIAL PERSONNEL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Greenawalt, Andrei M.','Employee',80000.00,'Per Annum','DEPUTY DIRECTOR OF CABINET AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Greene, Norman A.','Employee',66300.00,'Per Annum','DEPUTY DIRECTOR OF FINANCE');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Groth, Travis R.','Employee',42840.00,'Per Annum','STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Hable, Abigail K.','Employee',45000.00,'Per Annum','EXECUTIVE ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Hanson, Terry P.','Employee',42000.00,'Per Annum','DOMESTIC STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Harper, Ryan M.','Employee',56100.00,'Per Annum','DOMESTIC DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Harris, Kimberley D.','Employee',130500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND ASSOCIATE COUNSEL TO THE PRESIDENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Harris, Kevin R.','Employee',42000.00,'Per Annum','LEGISLATIVE ASSISTANT AND ASSISTANT TO THE HOUSE LIAISON');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Hash, Michael M.','Detailee',179700.00,'Per Annum','DEPUTY DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Hegde, Shilpa S.','Employee',42000.00,'Per Annum','ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Heimbach, James T.','Employee',130500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT FOR LEGISLATIVE AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Hennigan, Margo E.','Employee',45900.00,'Per Annum','ASSOCIATE DIRECTOR AND TRAVEL MANAGER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Hernandez, Philip M.','Employee',42000.00,'Per Annum','STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Hiatt, Natalie M.','Employee',42000.00,'Per Annum','OPERATOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Higginbottom, Heather A.','Employee',150000.00,'Per Annum','DEPUTY ASSISTANT TO THE PRESIDENT AND DEPUTY DIRECTOR OF THE DOMESTIC POLICY COUNCIL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Hitchcock, Adam S.','Employee',51000.00,'Per Annum','SPECIAL ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Hoang, Vy T.','Employee',44402.00,'Per Annum','RECORDS MANAGEMENT ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Hogan, Katherine J.','Employee',45900.00,'Per Annum','ASSOCIATE DIRECTOR OF PRESS ADVANCE AND PRESS POOL WRANGLER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Hogan, Nancy D.','Employee',145000.00,'Per Annum','DEPUTY ASSISTANT TO THE PRESIDENT AND DIRECTOR OF PRESIDENTIAL PERSONNEL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Hopkins, Marissa C.','Employee',60000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESS SECRETARY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Hornsby, Michael A.','Employee',66300.00,'Per Annum','ASSISTANT DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Hughes, Caroline E.','Employee',42000.00,'Per Annum','PRESS ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Hurley, Caitlin G.','Employee',60000.00,'Per Annum','ASSISTANT STAFF SECRETARY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Hurwitz, Sarah K.','Employee',100000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND SENIOR PRESIDENTIAL SPEECHWRITER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Inouye, Shinichi','Employee',78000.00,'Per Annum','DIRECTOR OF SPECIALITY MEDIA');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Jabbour, Mona K.','Employee',80000.00,'Per Annum','DEPUTY ASSOCIATE COUNSEL FOR PRESIDENTIAL PERSONNEL ');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Jackson, Deilia A. L.','Employee',42000.00,'Per Annum','DEPUTY ASSOCIATE DIRECTOR OF CORRESPONDENCE FOR THE FIRST LADY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Jackson, Elizabeth J.','Employee',37983.00,'Per Annum','RECORDS MANAGEMENT ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Jackson, Theresa R.','Employee',64439.00,'Per Annum','SHIFT LEADER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Jamison, Linda S.','Employee',113000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT FOR PRESIDENTIAL PERSONNEL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Jarrett, Valerie B.','Employee',172200.00,'Per Annum','SENIOR ADVISOR AND ASSISTANT TO THE PRESIDENT FOR INTERGOVERNMENTAL AFFAIRS AND PUBLIC ENGAGEMENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Jarvis, Kristen E.','Employee',51000.00,'Per Annum','SPECIAL ASSISTANT FOR SCHEDULING AND TRAVELING AIDE TO THE FIRST LADY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Jarvis-Shean, Elizabeth P.','Employee',100000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND DIRECTOR OF RESEARCH');

 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Jawando, William O.','Detailee',89033.00,'Per Annum','DEPUTY ASSOCIATE DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Jean-Pierre, Karine','Employee',76500.00,'Per Annum','NORTHEAST POLITICAL DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Johnson, Katherine B.','Employee',90000.00,'Per Annum','PERSONAL AIDE TO THE PRESIDENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Johnson, Linda M.','Employee',66335.00,'Per Annum','SHIFT LEADER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Johnston, Camille Y.','Employee',102000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND DIRECTOR OF COMMUNICATIONS FOR THE FIRST LADY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Jones, Crystal B.','Employee',84855.00,'Per Annum','ASSISTANT SUPERVISOR, DOCUMENT MANAGEMENT AND TRACKING UNIT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Jones, Elizabeth A.','Employee',100000.00,'Per Annum','DIRECTOR OF WHITE HOUSE ADMINISTRATION');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Jones, James L.','Employee',172200.00,'Per Annum','NATIONAL SECURITY ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Jones, Kristin T.','Employee',42000.00,'Per Annum','RESEARCH ASSOCIATE');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Jung, Bryan','Employee',50000.00,'Per Annum','SPECIAL ASSISTANT TO THE DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Juska, Monika','Employee',45000.00,'Per Annum','ASSOCIATE DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Kalbaugh, David E.','Employee',129758.00,'Per Annum','DEPUTY EXECUTIVE CLERK');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Kale, Katy A.','Employee',130500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND DIRECTOR OF WHITE HOUSE OPERATIONS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Kammerer, Chelsea J.','Employee',56100.00,'Per Annum','SPECIAL ASSISTANT TO THE DIRECTOR OF INTERGOVERNMENTAL AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Kang, Christopher D.','Employee',130500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT FOR LEGISLATIVE AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Kang, Eugene J.','Employee',48095.00,'Per Annum','SPECIAL PROJECTS COORDINATOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Keenan, Cody S.','Employee',75000.00,'Per Annum','PRESIDENTIAL SPEECHWRITER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Kelleher, Jr., Francis M.','Employee',110000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND DIRECTOR OF PRESIDENTIAL CORRESPONDENCE');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Kelly, Allison K.','Employee',45000.00,'Per Annum','VETTER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Kennedy, Joseph B.','Employee',42000.00,'Per Annum','STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Kennedy, Sean D.','Employee',130500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT FOR LEGISLATIVE AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Kiley, Bradley J.','Employee',162900.00,'Per Annum','ASSISTANT TO THE PRESIDENT FOR MANAGEMENT AND ADMINISTRATION');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Kim, Anna S.','Employee',60000.00,'Per Annum','ASSISTANT STAFF SECRETARY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Kimball, Astri B.','Employee',85000.00,'Per Annum','DEPUTY DIRECTOR OF CABINET AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('King, Taeshonnda C.','Employee',60232.00,'Per Annum','RECORDS MANAGEMENT ANALYST');

 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Kocher, Robert P.','Employee',130500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT FOR HEALTHCARE AND ECONOMIC POLICY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Kochman, Katherine H.','Employee',45000.00,'Per Annum','SCHEDULER FOR CHIEF OF STAFF');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Kohnke, Lisa J.','Employee',60000.00,'Per Annum','DEPUTY DIRECTOR OF ADVANCE AND SPECIAL EVENTS FOR THE OFFICE OF INTERGOVERNMENTAL AFFAIRS AND PUBLIC ENGAGEMENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Kommareddi, Madhuri','Employee',71400.00,'Per Annum','ASSOCIATE STAFF SECRETARY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Konwinski, Lisa M.','Employee',158500.00,'Per Annum','DEPUTY ASSISTANT TO THE PRESIDENT FOR LEGISLATIVE AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Koo, Stacy J.','Employee',55000.00,'Per Annum','DEPUTY ASSOCIATE DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Kramer, Douglas J.','Detailee',155500.00,'Per Annum','DEPUTY ASSOCIATE COUNSEL FOR PRESIDENTIAL PERSONNEL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Krass, Caroline D.','Employee',130500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND SPECIAL COUNSEL TO THE PRESIDENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Kravis, Jonathan I.','Employee',130500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND ASSOCIATE COUNSEL TO THE PRESIDENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Kumar, Pravin D.','Employee',50000.00,'Per Annum','ASSISTANT COUNSEL FOR NOMINATIONS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('LaBolt, Benjamin C.','Employee',78000.00,'Per Annum','ASSISTANT PRESS SECRETARY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Lartey, Solomon D.','Employee',56092.00,'Per Annum','RECORDS MANAGEMENT ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Larus, Anne K.','Employee',56100.00,'Per Annum','DEPUTY DIRECTOR AND HOTEL PROGRAM MANAGER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Lechtenberg, Tyler A','Employee',50000.00,'Per Annum','DIRECTOR OF CORRESPONDENCE FOR THE FIRST LADY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Ledbetter, Howli J.','Employee',42000.00,'Per Annum','COORDINATOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Lee, Gary S.','Employee',42000.00,'Per Annum','LEGISLATIVE ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Lee, Jesse C.','Employee',71400.00,'Per Annum','DIRECTOR OF ONLINE PROGRAMS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Leger, Daniella G.','Employee',102000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND DIRECTOR OF MESSAGE EVENTS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Lehrich, Matthew A.','Employee',65000.00,'Per Annum','MIDWESTERN REGIONAL COMMUNICATIONS DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Leitner-Laserna, Sofia I.','Employee',21000.00,'Per Annum','STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Lelyveld, Catherine M.','Employee',85680.00,'Per Annum','DIRECTOR AND PRESS SECRETARY TO THE FIRST LADY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Lepow, Brandon D.','Employee',55000.00,'Per Annum','SPECIAL ASSISTANT AND PRESS LEAD');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Lerner, Jeffrey B. W.','Employee',76500.00,'Per Annum','SOUTHERN POLITICAL DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Lesser, Eric P.','Employee',60000.00,'Per Annum','SPECIAL ASSISTANT TO THE SENIOR ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Levine, Jacob C.','Employee',45000.00,'Per Annum','POLICY ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Levine, Marne L.','Employee',130500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT FOR ECONOMIC POLICY AND CHIEF OF STAFF OF THE NATIONAL ECONOMIC COUNCIL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Lewin, Jesse M.','Employee',42000.00,'Per Annum','PRESS ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Lewis, Dana M.','Employee',66000.00,'Per Annum','SPECIAL ASSISTANT AND PERSONAL AIDE TO THE FIRST LADY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Lewis, Georgette T.','Employee',45000.00,'Per Annum','COORDINATOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Lewis, Kevin S.','Employee',42000.00,'Per Annum','PRESS ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Lezotte, Darin R.','Employee',62544.00,'Per Annum','RECORDS MANAGEMENT ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Liddell-Westefeld, Christopher','Employee',50000.00,'Per Annum','ASSISTANT DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Liegel, Christopher J.','Employee',37826.00,'Per Annum','RECORDS MANAGEMENT ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Lillie, Catherine E.','Employee',70000.00,'Per Annum','DIRECTOR OF PRESS ADVANCE');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Limon, Noerena','Employee',42000.00,'Per Annum','STAFF ASSISTANT');

 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Lippert, Mark W.','Employee',147500.00,'Per Annum','DEPUTY ASSISTANT TO THE PRESIDENT AND CHIEF OF STAFF FOR NATIONAL SECURITY OPERATIONS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Lipsky, Joshua S.','Employee',45000.00,'Per Annum','ASSOCIATE DIRECTOR OF PRESS ADVANCE ');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Lipton, David A.','Employee',149000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT FOR INTERNATIONAL ECONOMIC AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Loeb, Emily M.','Employee',60000.00,'Per Annum','LEGISLATIVE COUNSEL AND POLICY ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('London, Seth A.','Employee',45000.00,'Per Annum','LEGISLATIVE ASSISTANT AND ASSOCIATE DIRECTOR FOR LEGISLATIVE CORRESPONDENCE');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Lorjuste, Gregory','Employee',45900.00,'Per Annum','ASSOCIATE DIRECTOR OF SCHEDULING');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Love, Reginald L.','Employee',102000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND PERSONAL AIDE TO THE PRESIDENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Love, Timothy P.','Detailee',179700.00,'Per Annum','POLICY DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Lovett, Jonathan I.','Employee',75000.00,'Per Annum','PRESIDENTIAL SPEECHWRITER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Lu, Christopher P.','Employee',172200.00,'Per Annum','ASSISTANT TO THE PRESIDENT AND CABINET SECRETARY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Luck, Deatrice N.','Employee',43860.00,'Per Annum','SPECIAL SERVICES OPERATOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Lynn, Anthony V.','Employee',45000.00,'Per Annum','COORDINATOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Mack, William B.','Employee',80000.00,'Per Annum','DEPUTY ASSOCIATE COUNSEL FOR PRESIDENTIAL PERSONNEL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Mackey, Erin E.','Employee',66300.00,'Per Annum','DIRECTOR OF FINANCE');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Maher, Shawn P.','Employee',158500.00,'Per Annum','DEPUTY ASSISTANT TO THE PRESIDENT FOR LEGISLATIVE AFFAIRS AND SENATE LIAISION');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Markovitz, Alison J.','Employee',80000.00,'Per Annum','DEPUTY ASSOCIATE COUNSEL FOR PRESIDENTIAL PERSONNEL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Martin, Joanna G.','Employee',102000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT FOR PRESIDENTIAL PERSONNEL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Maska, Johanna M.','Employee',56100.00,'Per Annum','SPECIAL ASSISTANT AND PRESS LEAD');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Massey, Katherine','Detailee',165000.00,'Per Annum','SENIOR POLICY DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Mastromonaco, Alyssa M.','Employee',172200.00,'Per Annum','ASSISTANT TO THE PRESIDENT AND DIRECTOR OF SCHEDULING AND ADVANCE');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Mattson, Philip C.','Employee',60232.00,'Per Annum','SPECIAL ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Mayekar, Samir S.','Employee',56100.00,'Per Annum','NATIONAL SECURITY DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('McBride, Jonathan D.','Employee',130000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND DEPUTY DIRECTOR OF PRESIDENTIAL PERSONNEL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('McCarthy, Mary N.','Detailee',155500.00,'Per Annum','POLICY ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('McCathran, William W.','Employee',106839.00,'Per Annum','ASSISTANT EXECUTIVE CLERK');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('McDonough, Denis R.','Employee',147500.00,'Per Annum','DEPUTY ASSISTANT TO THE PRESIDENT AND NATIONAL SECURITY COUNCIL CHIEF OF STAFF');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('McGinnis, Patricia G.','Employee',0.00,'Per Annum','ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('McGrath, Shaun L.','Employee',93840.00,'Per Annum','DEPUTY DIRECTOR OF INTERGOVERNMENTAL AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('McGuire, MaryEllen C.','Employee',91800.00,'Per Annum','SENIOR POLICY ADVISOR FOR EDUCATION');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('McLaughlin, Margaret T.','Employee',120000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND CHIEF OF STAFF FOR PRESIDENTIAL PERSONNEL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('McNeal, Melissa K.','Employee',51000.00,'Per Annum','DIRECTOR OF WHITE HOUSE INTERNSHIP PROGRAM');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Mehrbani, Rodin A.','Employee',80000.00,'Per Annum','DEPUTY ASSOCIATE COUNSEL FOR PRESIDENTIAL PERSONNEL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Messina, James A.','Employee',172200.00,'Per Annum','ASSISTANT TO THE PRESIDENT AND DEPUTY CHIEF OF STAFF FOR OPERATIONS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Metcalf, Ryan D.','Employee',42000.00,'Per Annum','ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Milakofsky, Benjamin E.','Employee',45000.00,'Per Annum','SPECIAL ASSISTANT TO THE CABINET SECRETARY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Millett, Gregorio A.','Detailee',115731.00,'Per Annum','SENIOR POLICY ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Millison, Chad L.','Employee',60232.00,'Per Annum','RECORDS MANAGEMENT ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Miranda, Luis A.','Employee',78000.00,'Per Annum','DIRECTOR OF HISPANIC MEDIA');

 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Moilanen, Stephen S.','Employee',45000.00,'Per Annum','POLICY ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Monje, Jr., Carlos A.','Employee',91800.00,'Per Annum','SENIOR POLICY ADVISOR FOR SOCIAL INNOVATION AND CIVIC PARTICIPATION');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Monteiro, Darron P.','Employee',61200.00,'Per Annum','DEPUTY ASSOCIATE DIRECTOR OF PUBLIC ENGAGEMENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Mosteller, Brian D.','Employee',90000.00,'Per Annum','PERSONAL AIDE TO THE PRESIDENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Mrazek, Susannah R.','Employee',42000.00,'Per Annum','SENIOR ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Mueller, Lindsay E.','Employee',66300.00,'Per Annum','DIRECTOR OF OPERATIONS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Mu?ñoz, Cecilia','Employee',153500.00,'Per Annum','DEPUTY ASSISTANT TO THE PRESIDENT AND DIRECTOR OF INTERGOVERNMENTAL AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Muntz, Moira K. M.','Employee',66300.00,'Per Annum','NORTHEAST REGIONAL COMMUNICATIONS DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Murtha, Katherine R.','Employee',50000.00,'Per Annum','SENIOR VETTER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Nabors, Robert L.','Employee',162500.00,'Per Annum','DEPUTY ASSISTANT TO THE PRESIDENT AND SENIOR ADVISOR TO THE CHIEF OF STAFF');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Naidoff, Caitlin L.','Employee',50000.00,'Per Annum','EXECUTIVE ASSISTANT TO THE SENIOR ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Narechania, Saumya N.','Employee',50000.00,'Per Annum','ASSISTANT DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Nathan, Alison J.','Employee',130500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND ASSOCIATE COUNSEL TO THE PRESIDENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Neiman, Wanda M.','Employee',74958.00,'Per Annum','ASSISTANT TO THE EXECUTIVE CLERK');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Nelson, Elizabeth W.','Employee',45900.00,'Per Annum','ASSOCIATE DIRECTOR OF SCHEDULING');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Neralla, Venkateswar N.','Employee',75480.00,'Per Annum','PRIORITY PLACEMENT DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Newell, Peter J.','Employee',71400.00,'Per Annum','DIRECTOR OF TRAVEL OFFICE');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Nguyen, Alexander T. H.','Detailee',102829.00,'Per Annum','ETHICS ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Nicholson, Jr., Marvin D.','Employee',130000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND TRIP DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Noel, Pascal J.','Employee',59160.00,'Per Annum','SENIOR POLICY ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Northern, Mary G.','Employee',42000.00,'Per Annum','STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Ocampo, Maria L.','Employee',42000.00,'Per Annum','LEGISLATIVE ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('O Connor, Kyle P.','Employee',42000.00,'Per Annum','ASSISTANT SPEECHWRITER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Odintz, Joshua D.','Detailee',155500.00,'Per Annum','CHIEF TAX COUNSEL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Odio, Carlos P.','Employee',56100.00,'Per Annum','DEPUTY ASSOCIATE DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Offerman, Mary F.','Employee',45000.00,'Per Annum','DEPUTY ASSOCIATE DIRECTOR');


-- Insert into [dbo].[Employee](EmployeeName, EmployionTitle, SalaryeeStatus, PayBasis, Posit) values('Oleske, James M.','Employee',114000.00,'Per Annum','CHIEF OF STAFF, OFFICE OF LEGISLATIVE AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Olmos, Margaret C.','Employee',65000.00,'Per Annum','DEPUTY DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Olson, Elizabeth H.','Employee',76500.00,'Per Annum','DEPUTY DIRECTOR, PRESIDENTIAL CORRESPONDENCE');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('ONeil, Michael P.','Employee',81600.00,'Per Annum','PRIORITY PLACEMENT DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Onek, Matthew M.','Employee',110000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND CHIEF OF STAFF OF THE DOMESTIC POLICY COUNCIL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Ortiz, Michael R.','Employee',45000.00,'Per Annum','LEGISLATIVE ASSISTANT AND ASSISTANT TO THE DIRECTORS OFFICE');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Oxtoby, John T.','Employee',42000.00,'Per Annum','SPECIAL ASSISTANT TO THE SENIOR ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Page, Darienne M.','Employee',42000.00,'Per Annum','WEST WING RECEPTIONIST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Paige, Lauren R.','Employee',62000.00,'Per Annum','DIRECTOR OF SPECIAL PROJECTS FOR COMMUNICATIONS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Papa, Gregory J.','Employee',130500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT FOR LEGISLATIVE AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Papas, Nicholas W.','Detailee',92001.00,'Per Annum','DIRECTOR OF COMMUNICATIONS FOR THE OFFICE OF HEALTH REFORM');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Parker, Doris D.','Employee',79864.00,'Per Annum','ASSISTANT SUPERVISOR OF CLASSIFICATION');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Pate, Brian E.','Employee',46745.00,'Per Annum','PRESIDENTIAL SUPPORT SPECIALIST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Paulsen, Joseph B.','Employee',56100.00,'Per Annum','DEPUTY DIRECTOR AND SURROGATE SCHEDULER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Perez, Alejandro','Employee',130500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT FOR LEGISLATIVE AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Pfeiffer, Howard D.','Employee',172200.00,'Per Annum','ASSISTANT TO THE PRESIDENT AND DIRECTOR OF COMMUNICATIONS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Phadke, Shilpa','Employee',80000.00,'Per Annum','DEPUTY DIRECTOR OF CABINET AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Phillips, III, Robert M.','Employee',115000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND DIRECTOR OF NEW MEDIA');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Pipkins, Desiree E.','Employee',50000.00,'Per Annum','RESEARCH ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Pojman, Natalie R.','Employee',45900.00,'Per Annum','EXECUTIVE ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Pope, David F.','Employee',51000.00,'Per Annum','POLICY ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Pope, Jamal A.','Employee',42000.00,'Per Annum','STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Portilla, Zachary A.','Employee',42000.00,'Per Annum','PRIORITY PLACEMENT STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Posey, Stacie M.','Employee',42000.00,'Per Annum','ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Pourmorad, Araz ','Employee',45000.00,'Per Annum','ASSOCIATE DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Psaki, Jennifer R.','Employee',150000.00,'Per Annum','DEPUTY ASSISTANT TO THE PRESIDENT AND DEPUTY DIRECTOR OF COMMUNICATIONS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Pulliam, Allison C.','Employee',42000.00,'Per Annum','STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Quinn, Brian P.','Employee',45000.00,'Per Annum','ASSOCIATE DIRECTOR AND TRAVEL MANAGER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Raizk, Paul S.','Employee',113605.00,'Per Annum','DEPUTY DIRECTOR OF RECORDS MANAGEMENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Rathod, Nicholas S.','Employee',71400.00,'Per Annum','DEPUTY ASSOCIATE DIRECTOR OF INTERGOVERNMENTAL AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Reed, Ian P.','Employee',45900.00,'Per Annum','ASSOCIATE DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Reeves, Fiona O.','Employee',51000.00,'Per Annum','SENIOR WRITER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Reinstein, Joseph B.','Employee',66300.00,'Per Annum','DEPUTY DIRECTOR AND DEPUTY SOCIAL SECRETARY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Richardson, Karen E.','Detailee',92001.00,'Per Annum','ASSOCIATE DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Rittner, Kathleen A.','Detailee',144868.00,'Per Annum','ETHICS ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Rivadeneira, Shirley C.','Employee',55000.00,'Per Annum','ENERGY AND ENVIRONMENT DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Roach, Cynthia L.','Employee',100904.00,'Per Annum','SUPERVISOR OF CLASSIFICATION');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Roberts, Blake C.','Employee',99000.00,'Per Annum','DEPUTY ASSOCIATE COUNSEL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Robertson, Ian T.','Employee',42000.00,'Per Annum','ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Roche, Mary K.','Employee',60000.00,'Per Annum','SPEECHWRITER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Roddick, Gertrude A.','Employee',89846.00,'Per Annum','SPECIAL ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Rodriguez, Roberto J.','Employee',120000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT FOR EDUCATION POLICY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Rosalsky, Gregory E.','Employee',45000.00,'Per Annum','VETTER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Rouse, Peter M.','Employee',172200.00,'Per Annum','ASSISTANT TO THE PRESIDENT AND SENIOR ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Ruemmler, Kathryn H.','Employee',158500.00,'Per Annum','DEPUTY ASSISTANT TO THE PRESIDENT AND DEPUTY COUNSEL TO THE PRESIDENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Ruemmler, Michael L.','Employee',56100.00,'Per Annum','SPECIAL ASSISTANT AND ADVANCE LEAD');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Rundlet, Peter F.','Employee',158500.00,'Per Annum','DEPUTY ASSISTANT TO THE PRESIDENT AND DEPUTY STAFF SECRETARY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Ryan, Timothy J.','Employee',71400.00,'Per Annum','DIRECTOR OF TECHNOLOGY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Sabochik, Katelyn A.','Employee',62500.00,'Per Annum','DEPUTY DIRECTOR, ONLINE PROGRAMS AND EMAIL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Sahgal, Rishi R.','Employee',66300.00,'Per Annum','DIRECTOR OF WHITE HOUSE PERSONNEL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Samuels, Jr., Wendell A.','Employee',60232.00,'Per Annum','RECORDS MANAGEMENT ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Samuels, Jonathan D.','Employee',130500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT FOR LEGISLATIVE AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Sanders, Trooper','Employee',85000.00,'Per Annum','DEPUTY DIRECTOR OF POLICY AND PROJECTS FOR THE FIRST LADY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Santucci, Laura G.','Employee',70000.00,'Per Annum','DEPUTY REGIONAL POLITICAL DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Sass, Joan C.','Employee',56791.00,'Per Annum','ASSISTANT SHIFT LEADER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Sathe, Smrthi','Employee',70000.00,'Per Annum','ASSOCIATE DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Saunders, George T.','Employee',155500.00,'Per Annum','EXECUTIVE CLERK');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Schafer, Ellie S.','Employee',71400.00,'Per Annum','DIRECTOR OF VISITORS OFFICE');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Schaub, Matthew J.','Employee',42000.00,'Per Annum','ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Schiliro, Philip M.','Employee',172200.00,'Per Annum','ASSISTANT TO THE PRESIDENT AND DIRECTOR, OFFICE OF LEGISLATIVE AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Schmuck, Robert E.','Employee',42000.00,'Per Annum','STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Schuker, Daniel J. T.','Employee',55080.00,'Per Annum','POLICY ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Schulman, Kori S.','Employee',48450.00,'Per Annum','ASSOCIATE DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Schwartz, Alison K.','Employee',75000.00,'Per Annum','WESTERN POLITICAL DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Setser, Bradley W.','Employee',110500.00,'Per Annum','DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Seymour, Jennifer D.','Detailee',107770.00,'Per Annum','POLICY ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Shah, Sonal R.','Employee',120000.00,'Per Annum','DEPUTY ASSISTANT TO THE PRESIDENT AND DIRECTOR, OFFICE  OF SOCIAL INNOVATION AND CIVIC PARTICIPATION');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Shapiro, Nicholas S.','Employee',78000.00,'Per Annum','ASSISTANT PRESS SECRETARY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Shaw, Katherine','Employee',130500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND ASSOCIATE COUNSEL TO THE PRESIDENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Sheehy, Kristin J.','Employee',60000.00,'Per Annum','SPECIAL ASSISTANT TO THE DEPUTY CHIEF OF STAFF');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Sher, Susan S.','Employee',172200.00,'Per Annum','ASSISTANT TO THE PRESIDENT, CHIEF OF STAFF TO THE FIRST LADY AND COUNSEL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Showers, Wendy W.','Employee',84855.00,'Per Annum','PRESIDENTIAL SUPPORT SPECIALIST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Sibley, Sarah E.','Employee',50000.00,'Per Annum','SENIOR WRITER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Siegel, Avra C.','Employee',50000.00,'Per Annum','SPECIAL ASSISTANT TO THE DEPUTY ASSISTANT TO THE PRESIDENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Simas, David M.','Employee',100000.00,'Per Annum','DIRECTOR OF SPECIAL PROJECTS AND SPECIAL ASSISTANT TO THE SENIOR ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Singiser, Dana E.','Employee',130500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT FOR LEGISLATIVE AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Sinha, Manish','Employee',42000.00,'Per Annum','OPERATIONS STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Sirbu, Mara L.','Employee',42000.00,'Per Annum','NATIONAL SECURITY STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Skoczek, Timothy R.','Employee',45000.00,'Per Annum','DEPUTY DIRECTOR OF RESPONSE');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Smith, Elizabeth S.','Employee',130000.00,'Per Annum','DEPUTY ASSISTANT TO THE PRESIDENT AND DEPUTY CABINET SECRETARY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Smith, Jason J.','Employee',42000.00,'Per Annum','SENIOR ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Smith, Kelley S.','Employee',42000.00,'Per Annum','SENIOR ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Smoot, Julianna S.','Employee',150000.00,'Per Annum','DEPUTY ASSISTANT TO THE PRESIDENT AND WHITE HOUSE SOCIAL SECRETARY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Sobel, Charlie J.','Employee',55000.00,'Per Annum','DIRECTOR OF OPERATIONS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Spencer, Jane C.','Employee',76500.00,'Per Annum','MIDWEST POLITICAL DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Starkey, Frances M.','Employee',80000.00,'Per Annum','DIRECTOR OF SCHEDULING AND ADVANCE FOR THE FIRST LADY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Stephens, Jeffrey M.','Employee',75000.00,'Per Annum','DEPUTY DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Stephens, Semonti M.','Employee',53550.00,'Per Annum','ASSOCIATE DIRECTOR AND DEPUTY PRESS SECRETARY TO THE FIRST LADY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Stickel, Nicole T.','Employee',42000.00,'Per Annum','SENIOR ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Stoev, Ivan','Employee',50000.00,'Per Annum','ASSISTANT DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Stone, Wandra E.','Employee',112774.00,'Per Annum','SUPERVISOR OF SEARCH AND FILE');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Stoneman, Shelly O.','Employee',130500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT FOR LEGISLATIVE AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Stracko, Jill A.','Employee',51000.00,'Per Annum','ASSISTANT DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Strautmanis, Michael A.','Employee',139500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND CHIEF OF STAFF OF THE OFFICE OF INTERGOVERNMENTAL AFFAIRS AND PUBLIC ENGAGEMENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Summers, Lawrence H.','Employee',172200.00,'Per Annum','ASSISTANT TO THE PRESIDENT FOR ECONOMIC POLICY AND DIRECTOR OF THE NATIONAL ECONOMIC COUNCIL');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Sutphen, Mona K.','Employee',172200.00,'Per Annum','ASSISTANT TO THE PRESIDENT AND DEPUTY CHIEF OF STAFF FOR POLICY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Sutton, Nikki E.','Employee',47500.00,'Per Annum','ASSOCIATE DIRECTOR, NEW MEDIA OPERATIONS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Swanson, Gregory C.','Employee',42000.00,'Per Annum','SENIOR ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Sweeney, Sean F.','Employee',120000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND DIRECTOR, OFFICE OF THE CHIEF OF STAFF');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Swire, Peter P.','Employee',130500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT FOR ECONOMIC POLICY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Taggart, Jr., Hugh T.','Employee',92341.00,'Per Annum','ASSISTANT SUPERVISOR OF SEARCH AND FILE');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Tamarin, Nathanael P.','Employee',96900.00,'Per Annum','ASSOCIATE DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Tate-Gilmore, Ashley R.','Employee',45900.00,'Per Annum','ASSOCIATE DIRECTOR AND TRAVEL MANAGER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Tchen, Christina M.','Employee',153500.00,'Per Annum','DEPUTY ASSISTANT TO THE PRESIDENT AND DIRECTOR OF THE OFFICE OF PUBLIC ENGAGEMENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Teehee, Kimberly K.','Employee',100000.00,'Per Annum','SENIOR POLICY ADVISOR FOR NATIVE AMERICAN AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Tennison, Angela N.','Employee',42000.00,'Per Annum','STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Terrell, Louisa M.','Employee',130500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT FOR LEGISLATIVE AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Terry, Joelle L.','Employee',65000.00,'Per Annum','DEPUTY DIRECTOR OF MESSAGE EVENTS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Thomas, III, Edwin R.','Employee',97936.00,'Per Annum','ASSISTANT EXECUTIVE CLERK');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Thomas, Maria A.','Employee',42000.00,'Per Annum','STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Thorbjornsen, Lauren K.','Employee',45000.00,'Per Annum','EXECUTIVE ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Trainor, Gregory T.','Employee',68230.00,'Per Annum','SPECIAL ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Tranchin, Matthew A.','Employee',42000.00,'Per Annum','STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Tseggai, Gannet L.','Employee',66300.00,'Per Annum','COMMUNICATIONS ADVISOR, DOMESTIC POLICY COUNCIL AND OFFICE OF NATIONAL AIDS POLICY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Tubman, Samantha J.','Employee',49000.00,'Per Annum','DEPUTY ASSOCIATE DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Tucci, Rosarie G.','Employee',51000.00,'Per Annum','SENIOR WRITER');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Tucker, Phyllis J.','Employee',89033.00,'Per Annum','SUPERVISOR OF COMPUTER ADMINISTRATION');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Turk, Andrea E.','Employee',50000.00,'Per Annum','DIRECTOR OF INFORMATION SERVICES');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Turton, Daniel A.','Employee',158500.00,'Per Annum','DEPUTY ASSISTANT TO THE PRESIDENT FOR LEGISLATIVE AFFAIRS AND HOUSE LIAISON');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Utech, Daniel G.','Detailee',130000.00,'Per Annum','ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Vale, Elizabeth A.','Detailee',132009.00,'Per Annum','WHITE HOUSE BUSINESS LIAISON');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Valencia, Stephanie M.','Employee',61200.00,'Per Annum','DEPUTY ASSOCIATE DIRECTOR OF PUBLIC ENGAGEMENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Vanderslice, Mara L.','Detailee',92001.00,'Per Annum','POLICY ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Vega, Dagoberto','Employee',100000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND DIRECTOR OF BROADCAST MEDIA');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Verrilli, Donald B.','Employee',158500.00,'Per Annum','DEPUTY ASSISTANT TO THE PRESIDENT AND DEPUTY COUNSEL TO THE PRESIDENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Vietor, Thomas F.','Employee',78000.00,'Per Annum','ASSISTANT PRESS SECRETARY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Vogel, Matthew A.','Employee',71400.00,'Per Annum','ASSOCIATE DIRECTOR OF COMMUNICATIONS FOR ECONOMICS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Voorman, David A.','Employee',45594.00,'Per Annum','RECORDS MANAGEMENT ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Wade, David L.','Employee',55000.00,'Per Annum','ASSOCIATE DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Wade, Frances J.','Employee',44402.00,'Per Annum','RECORDS MANAGEMENT ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Walsh, Joan L.','Employee',60000.00,'Per Annum','ASSISTANT STAFF SECRETARY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Wang-Levine, Adam','Employee',55080.00,'Per Annum','POLICY ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Watkins, Kyle D. ','Employee',45000.00,'Per Annum','SPECIAL ASSISTANT TO THE DEPUTY ASSISTANT TO THE PRESIDENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Watson, Takesha R.','Employee',43860.00,'Per Annum','SPECIAL SERVICES OPERATOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Wear, Michael R.','Employee',45900.00,'Per Annum','EXECUTIVE ASSISTANT TO THE EXECUTIVE DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Webster, Meridith A.','Employee',120000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND SENIOR ADVISOR TO THE CHIEF OF STAFF');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Weiser, Philip J.','Detailee',172000.00,'Per Annum','SENIOR ADVISOR FOR TECHNOLOGY AND INNOVATION TO THE NATIONAL ECONOMIC COUNCIL DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Whichard, IV, David J.','Employee',45900.00,'Per Annum','ASSOCIATE DIRECTOR AND TRIP COORDINATOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('White, Cleo','Detailee',65393.00,'Per Annum','ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Whitty, Patrick M.','Employee',45000.00,'Per Annum','EXECUTIVE ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Williams, Marie J.','Employee',55000.00,'Per Annum','BOARDS AND COMMISSIONS DIRECTOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Williams, Sherman A.','Employee',74958.00,'Per Annum','ASSISTANT TO THE EXECUTIVE CLERK');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Wilson, Denise R.','Employee',130500.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT FOR LEGISLATIVE AFFAIRS');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Wilson, Samuel A.','Employee',45000.00,'Per Annum','DEPUTY DIRECTOR FOR BROADCAST MEDIA');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Winter, Melissa','Employee',102000.00,'Per Annum','SPECIAL ASSISTANT TO THE PRESIDENT AND DEPUTY CHIEF OF STAFF TO THE FIRST LADY');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Witt, Abigail','Employee',45000.00,'Per Annum','SPECIAL ASSISTANT TO THE CHIEF OF STAFF OF THE OFFICE OF INTERGOVERNMENTAL AFFAIRS AND PUBLIC ENGAGEMENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Wong, Shale L.','Employee',0.00,'Per Annum','POLICY ADVISOR');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Wright, Jessica N.','Employee',96900.00,'Per Annum','DEPUTY DIRECTOR OF SCHEDULING FOR THE PRESIDENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Yeager Kaplan, Jennifer F.','Employee',66300.00,'Per Annum','SPECIAL ASSISTANT TO THE DIRECTOR OF PUBLIC ENGAGEMENT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Young, Jr., Reginald D.','Employee',60232.00,'Per Annum','RECORDS MANAGEMENT ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Young, Katherine H.','Employee',42000.00,'Per Annum','STAFF ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Young, Latoya A.','Employee',58511.00,'Per Annum','RECORDS MANAGEMENT ANALYST');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Zelman, Allison L.','Employee',50000.00,'Per Annum','POLICY ASSISTANT');
 Insert into [dbo].[Employee](EmployeeName, EmployeeStatus, Salary, PayBasis, PositionTitle) values('Zichal, Heather R.','Employee',100000.00,'Per Annum','DEPUTY ASSISTANT TO THE PRESIDENT FOR ENERGY AND CLIMATE CHANGE');
